### ISSUE TITLE
Can't install on Xiaomi Redmi Note 4X: can't mount /vendor

### ISSUE THREAD

**Issue by spidey** [Jerry981028/Magisk#1]
This fork was supposed to have pre-compiled versions of latest Magisk with PR 373 (https://github.com/topjohnwu/Magisk/pull/373) integrated, but the error still reproduces on my device.

This or the official Magisk's both can't be flashed with the exact same message. My device has a /cust partition intead of /vendor. I'm using ResurrectionRemix 6 treble from https://forum.xda-developers.com/redmi-note-4/xiaomi-redmi-note-4-snapdragon-roms-kernels-recoveries--other-development/rom-resurrection-remix-v6-0-0-t3748465, with RedWolf recovery (linked in the RR thread). Tried using both the Magisk from the thread and this one, without success. Also tried official Magisk, same error.

**Comment by spidey** [comment]
I've also patched over RR the latest firmware for my device, supposedly from Xiaomi, from this thread: https://forum.xda-developers.com/redmi-note-4/xiaomi-redmi-note-4-snapdragon-roms-kernels-recoveries--other-development/firmware-xiaomi-redmi-note-4-t3760917

**Comment by isjerryxiao** [comment]
You may try another recovery.

**Comment by spidey** [comment]
Yeah, managed to flash with RedWolf treble cust build. Sorry for implying the bug was on this fork.
