### ISSUE TITLE
MagiskHide not active on reboot

### ISSUE THREAD

**Issue by pythonimus** [Jerry981028/Magisk#4]
Im with my Mi Mix 2 on LOS 15.1.
Every time I reboot I have to go to settings and disable "Magisk Hide" and reenable it (then SafetyNet passes).
Logcat attached:
1. rebooted my system
2. started magisk manager and did a SafetyNet check (both failed)
3. toggled "Magisk Hide" setting to off, and then to on
4. SafetyNet check again, both passed
 
[2018-07-12-08-53-22.txt](https://github.com/Jerry981028/Magisk/files/2194775/2018-07-12-08-53-22.txt)

I think I know what the problem is here, persist.magisk.hide is deleted on reboot.
When I create persist.magisk.hide and set (to 1) with MagiskHide Props Config I pass SafetyNet check on reboot, but somehow its not fast enough (?) so the Playstore checks safetynet (and fails) before Magisk can pass it...

**Comment by isjerryxiao** [comment]
I don't think it's my problem. Please consider reporting it to @topjohnwu.

>  but somehow its not fast enough (?) so the Playstore checks safetynet (and fails) before Magisk can pass it...  

Have you tried clearing data of Google Play Store?

**Comment by isjerryxiao** [comment]
Close #4
I'm going to archive this repo.
